BASE_THEME = {
    "bg": "#f3f6fb",
    "panel": "rgba(255, 255, 255, 0.92)",
    "panelAlt": "#f7f9fc",
    "line": "#d8e0ee",
    "lineStrong": "#bcc8db",
    "text": "#213044",
    "muted": "#627188",
    "blue": "#2d68b2",
    "blueSoft": "#ecf3ff",
    "blueDeep": "#173762",
    "warm": "#eef2f8",
    "selection": "#d8e9ff",
    "selectionBorder": "#7da6e8",
}


THEME_OPTIONS = [
    {
        "id": "slate",
        "label": "Slate",
        "preview": ["#f3f6fb", "#ffffff", "#2d68b2", "#173762"],
        "colors": {},
    },
    {
        "id": "sand",
        "label": "Sand",
        "preview": ["#f8f3eb", "#fff8f0", "#a9602a", "#74401a"],
        "colors": {
            "bg": "#f8f3eb",
            "panel": "rgba(255, 255, 255, 0.92)",
            "panelAlt": "#fdf7ef",
            "line": "#e5d8c7",
            "lineStrong": "#d7c2a8",
            "text": "#3c2d24",
            "muted": "#7c6c62",
            "blue": "#a9602a",
            "blueSoft": "#fff0e3",
            "blueDeep": "#74401a",
            "warm": "#f4e5d7",
            "selection": "#ffe3c8",
            "selectionBorder": "#dc9964",
        },
    },
    {
        "id": "sage",
        "label": "Sage",
        "preview": ["#eef5f0", "#ffffff", "#45715a", "#284938"],
        "colors": {
            "bg": "#eef5f0",
            "panel": "rgba(255, 255, 255, 0.92)",
            "panelAlt": "#f3f8f4",
            "line": "#d2e0d6",
            "lineStrong": "#aec4b4",
            "text": "#23352d",
            "muted": "#5e7568",
            "blue": "#45715a",
            "blueSoft": "#e7f3eb",
            "blueDeep": "#284938",
            "warm": "#e2efe6",
            "selection": "#d9ede2",
            "selectionBorder": "#78a287",
        },
    },
    {
        "id": "linen",
        "label": "Linen",
        "preview": ["#fbfaf7", "#fff6ee", "#9d6a3d", "#5e3a1c"],
        "colors": {
            "bg": "#fbfaf7",
            "panel": "#fff6ee",
            "panelAlt": "#fffaf5",
            "line": "#ead7c2",
            "lineStrong": "#d4b99c",
            "text": "#39281d",
            "muted": "#786557",
            "blue": "#9d6a3d",
            "blueSoft": "#fff0e0",
            "blueDeep": "#5e3a1c",
            "warm": "#f5e7da",
            "selection": "#ffe4c6",
            "selectionBorder": "#c88d55",
        },
    },
    {
        "id": "harbor",
        "label": "Harbor",
        "preview": ["#f2f7fb", "#ffffff", "#2f7e9e", "#13465c"],
        "colors": {
            "bg": "#f2f7fb",
            "panel": "rgba(255, 255, 255, 0.94)",
            "panelAlt": "#f4fbfd",
            "line": "#d5e7ef",
            "lineStrong": "#a9c8d5",
            "text": "#17333f",
            "muted": "#5c7885",
            "blue": "#2f7e9e",
            "blueSoft": "#e3f4fb",
            "blueDeep": "#13465c",
            "warm": "#e8f1f5",
            "selection": "#d8eef8",
            "selectionBorder": "#5da4c4",
        },
    },
    {
        "id": "coral",
        "label": "Coral",
        "preview": ["#fff8f6", "#ffffff", "#da6b58", "#82352a"],
        "colors": {
            "bg": "#fff8f6",
            "panel": "rgba(255, 255, 255, 0.94)",
            "panelAlt": "#fff3ef",
            "line": "#f0d8d1",
            "lineStrong": "#dfb2a7",
            "text": "#402520",
            "muted": "#87615a",
            "blue": "#da6b58",
            "blueSoft": "#ffe6e0",
            "blueDeep": "#82352a",
            "warm": "#f9e5df",
            "selection": "#ffd6cf",
            "selectionBorder": "#df8d7f",
        },
    },
    {
        "id": "citrus",
        "label": "Citrus",
        "preview": ["#fffdf5", "#ffffff", "#b68a19", "#69500c"],
        "colors": {
            "bg": "#fffdf5",
            "panel": "rgba(255, 255, 255, 0.94)",
            "panelAlt": "#fff9df",
            "line": "#eee3b4",
            "lineStrong": "#d6c372",
            "text": "#3c3312",
            "muted": "#74683f",
            "blue": "#b68a19",
            "blueSoft": "#fff3bf",
            "blueDeep": "#69500c",
            "warm": "#f6efc9",
            "selection": "#fbe7a7",
            "selectionBorder": "#c7a43f",
        },
    },
    {
        "id": "ember",
        "label": "Ember",
        "preview": ["#fff6f1", "#fff9f6", "#c76632", "#6b2f10"],
        "colors": {
            "bg": "#fff6f1",
            "panel": "#fff9f6",
            "panelAlt": "#fff0e7",
            "line": "#eccdbe",
            "lineStrong": "#d79a79",
            "text": "#3f271d",
            "muted": "#7d5e4f",
            "blue": "#c76632",
            "blueSoft": "#ffe1d0",
            "blueDeep": "#6b2f10",
            "warm": "#f7dfd2",
            "selection": "#ffd0b6",
            "selectionBorder": "#d27f55",
        },
    },
    {
        "id": "berry",
        "label": "Berry",
        "preview": ["#fcf5fa", "#fff9fd", "#ae4f83", "#5e2447"],
        "colors": {
            "bg": "#fcf5fa",
            "panel": "#fff9fd",
            "panelAlt": "#fdf0f8",
            "line": "#ecd1e1",
            "lineStrong": "#d3a2bd",
            "text": "#362030",
            "muted": "#73576a",
            "blue": "#ae4f83",
            "blueSoft": "#f9dff0",
            "blueDeep": "#5e2447",
            "warm": "#f6e4ef",
            "selection": "#f7cfe6",
            "selectionBorder": "#c47aa3",
        },
    },
    {
        "id": "marina",
        "label": "Marina",
        "preview": ["#f3f8fd", "#ffffff", "#2563c9", "#15326d"],
        "colors": {
            "bg": "#f3f8fd",
            "panel": "rgba(255, 255, 255, 0.95)",
            "panelAlt": "#eef5ff",
            "line": "#d2e0f6",
            "lineStrong": "#9fb8e3",
            "text": "#18304c",
            "muted": "#60738b",
            "blue": "#2563c9",
            "blueSoft": "#dfeaff",
            "blueDeep": "#15326d",
            "warm": "#e4edf9",
            "selection": "#ccddff",
            "selectionBorder": "#6f95da",
        },
    },
    {
        "id": "glacier",
        "label": "Glacier",
        "preview": ["#f4fbfd", "#f8feff", "#3f93a9", "#1c4d5a"],
        "colors": {
            "bg": "#f4fbfd",
            "panel": "#f8feff",
            "panelAlt": "#edf8fb",
            "line": "#d4e8ee",
            "lineStrong": "#9cc4cf",
            "text": "#1d3640",
            "muted": "#607983",
            "blue": "#3f93a9",
            "blueSoft": "#ddf4fa",
            "blueDeep": "#1c4d5a",
            "warm": "#e2f0f4",
            "selection": "#cfeef5",
            "selectionBorder": "#69aebf",
        },
    },
    {
        "id": "forest",
        "label": "Forest",
        "preview": ["#f2f7f2", "#f8fcf8", "#3e7f46", "#214726"],
        "colors": {
            "bg": "#f2f7f2",
            "panel": "#f8fcf8",
            "panelAlt": "#edf6ee",
            "line": "#d0e2d2",
            "lineStrong": "#9eb8a2",
            "text": "#203325",
            "muted": "#5e7562",
            "blue": "#3e7f46",
            "blueSoft": "#ddf0e0",
            "blueDeep": "#214726",
            "warm": "#dfeee1",
            "selection": "#cfe6d2",
            "selectionBorder": "#6ca874",
        },
    },
    {
        "id": "graphite",
        "label": "Graphite",
        "preview": ["#f3f4f7", "#ffffff", "#57657a", "#232a36"],
        "colors": {
            "bg": "#f3f4f7",
            "panel": "rgba(255, 255, 255, 0.95)",
            "panelAlt": "#f0f2f6",
            "line": "#d7dce6",
            "lineStrong": "#afb8c9",
            "text": "#232a36",
            "muted": "#667286",
            "blue": "#57657a",
            "blueSoft": "#e6ebf2",
            "blueDeep": "#232a36",
            "warm": "#eaedf3",
            "selection": "#dce4f0",
            "selectionBorder": "#8797af",
        },
    },
    {
        "id": "ivory-pop",
        "label": "Ivory Pop",
        "preview": ["#ffffff", "#eaf2ff", "#2d68b2", "#ff8a65"],
        "colors": {
            "bg": "#ffffff",
            "panel": "#eef4ff",
            "panelAlt": "#fff7f0",
            "line": "#d6e0f4",
            "lineStrong": "#a8badf",
            "text": "#24334b",
            "muted": "#657690",
            "blue": "#2d68b2",
            "blueSoft": "#dde9ff",
            "blueDeep": "#173762",
            "warm": "#ffe5d7",
            "selection": "#d8e6ff",
            "selectionBorder": "#7ea5ea",
        },
    },
    {
        "id": "paper-garden",
        "label": "Paper Garden",
        "preview": ["#ffffff", "#edf7ee", "#4f8c60", "#d8eadb"],
        "colors": {
            "bg": "#ffffff",
            "panel": "#edf7ee",
            "panelAlt": "#f8fcf9",
            "line": "#d4e6d7",
            "lineStrong": "#a6c7ad",
            "text": "#223428",
            "muted": "#617566",
            "blue": "#4f8c60",
            "blueSoft": "#def1e2",
            "blueDeep": "#285137",
            "warm": "#e5f0e8",
            "selection": "#d2e9d8",
            "selectionBorder": "#77ab84",
        },
    },
    {
        "id": "paper-rose",
        "label": "Paper Rose",
        "preview": ["#ffffff", "#fff1f5", "#be5b88", "#ffe2eb"],
        "colors": {
            "bg": "#ffffff",
            "panel": "#fff1f5",
            "panelAlt": "#fff9fb",
            "line": "#efd1dd",
            "lineStrong": "#d6a2ba",
            "text": "#3a2430",
            "muted": "#7c6170",
            "blue": "#be5b88",
            "blueSoft": "#ffdbe8",
            "blueDeep": "#6e2a4c",
            "warm": "#fde7ee",
            "selection": "#ffd1e1",
            "selectionBorder": "#cf7fa4",
        },
    },
    {
        "id": "paper-citrus",
        "label": "Paper Citrus",
        "preview": ["#ffffff", "#fff8d9", "#bc8b08", "#ffe594"],
        "colors": {
            "bg": "#ffffff",
            "panel": "#fff8d9",
            "panelAlt": "#fffdf1",
            "line": "#ebdd95",
            "lineStrong": "#d1b859",
            "text": "#3f330f",
            "muted": "#78693e",
            "blue": "#bc8b08",
            "blueSoft": "#fff0b7",
            "blueDeep": "#6c4f02",
            "warm": "#fff0b9",
            "selection": "#ffe999",
            "selectionBorder": "#c8a339",
        },
    },
    {
        "id": "midnight",
        "label": "Midnight",
        "preview": ["#eef2fb", "#dde6fb", "#385ea8", "#1a2b52"],
        "colors": {
            "bg": "#eef2fb",
            "panel": "#dde6fb",
            "panelAlt": "#f4f7ff",
            "line": "#c9d5f0",
            "lineStrong": "#95a8d8",
            "text": "#23324f",
            "muted": "#65749a",
            "blue": "#385ea8",
            "blueSoft": "#d9e5ff",
            "blueDeep": "#1a2b52",
            "warm": "#e1e7f5",
            "selection": "#d3def8",
            "selectionBorder": "#6e88c3",
        },
    },
    {
        "id": "aurora",
        "label": "Aurora",
        "preview": ["#f4f8ff", "#eefaf7", "#6b5cff", "#14b8a6"],
        "colors": {
            "bg": "#f4f8ff",
            "panel": "rgba(255, 255, 255, 0.92)",
            "panelAlt": "#eefaf7",
            "line": "#d6dff7",
            "lineStrong": "#a8b5e1",
            "text": "#232a45",
            "muted": "#677291",
            "blue": "#6b5cff",
            "blueSoft": "#e4e2ff",
            "blueDeep": "#2f2775",
            "warm": "#dcf5ef",
            "selection": "#d8e3ff",
            "selectionBorder": "#8f87ff",
        },
    },
    {
        "id": "terracotta",
        "label": "Terracotta",
        "preview": ["#fbf2ee", "#fff8f5", "#b85c38", "#6a2c18"],
        "colors": {
            "bg": "#fbf2ee",
            "panel": "#fff8f5",
            "panelAlt": "#fcebe4",
            "line": "#e7cfc4",
            "lineStrong": "#cd9b86",
            "text": "#3d271f",
            "muted": "#785d53",
            "blue": "#b85c38",
            "blueSoft": "#f8ded4",
            "blueDeep": "#6a2c18",
            "warm": "#f2ddd5",
            "selection": "#f5d0c0",
            "selectionBorder": "#c77b5b",
        },
    },
    {
        "id": "cypress",
        "label": "Cypress",
        "preview": ["#eef7f6", "#ffffff", "#2f7b73", "#174843"],
        "colors": {
            "bg": "#eef7f6",
            "panel": "rgba(255, 255, 255, 0.94)",
            "panelAlt": "#e6f2f0",
            "line": "#cde0dd",
            "lineStrong": "#9fc0bb",
            "text": "#1f3432",
            "muted": "#627a78",
            "blue": "#2f7b73",
            "blueSoft": "#d9efeb",
            "blueDeep": "#174843",
            "warm": "#deeeeb",
            "selection": "#cce8e3",
            "selectionBorder": "#62a299",
        },
    },
    {
        "id": "random",
        "label": "Random",
        "preview": ["#2d68b2", "#da6b58", "#4f8c60", "#be5b88"],
        "colors": {},
        "isRandom": True,
    },
]


THEME_MAP = {}
for option in THEME_OPTIONS:
    if option.get("isRandom"):
        continue
    merged = dict(BASE_THEME)
    merged.update(option["colors"])
    THEME_MAP[option["id"]] = {
        "id": option["id"],
        "label": option["label"],
        "preview": option["preview"],
        "colors": merged,
    }


THEME_CHOICES = {option["id"] for option in THEME_OPTIONS}


def theme_options_payload():
    payload = []
    for option in THEME_OPTIONS:
        item = {
            "id": option["id"],
            "label": option["label"],
            "preview": option["preview"],
        }
        if option.get("isRandom"):
            item["isRandom"] = True
        else:
            item["colors"] = THEME_MAP[option["id"]]["colors"]
        payload.append(item)
    return payload
